<a href="https://colab.research.google.com/github/PRITHASAMANTA/Basic_Python/blob/main/NUMPYipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

PYTHON list can store only one dimensional array. and it can be any type!
but in numpy we can store multi dimensional array

In [ ]:
#python list :
list=[1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [ ]:
#Numpy array
print("1D array:")
a=np.array([1,2,3,4,5])
print(a)

print("2D array:")
b = np.array([[1,2,3,4],
             [5,6,7,8]])
print(b)

1D array:
[1 2 3 4 5]
2D array:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print("3d array")
c = np.array([[[1,2,3,4],
             [5,6,7,8],
               [11,23,45,67]]])
print(c)

3d array
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [11 23 45 67]]]


SIZE OF ARRAY ELEMENT


In [ ]:
print(a.size)
print(b.size)

5
8


shape(rows,column)

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 4)
(1, 3, 4)


In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [ ]:
c.transpose()

array([[[ 1],
        [ 5],
        [11]],

       [[ 2],
        [ 6],
        [23]],

       [[ 3],
        [ 7],
        [45]],

       [[ 4],
        [ 8],
        [67]]])

np.arrange(start,end,step)**bold text**

In [ ]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a=np.arange(1,20,2) #odd number
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
#arr.reshape(rows,col)
a=a.reshape((3,3))
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
a=np.arange(1,100,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
a=a.reshape((10,5))
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [ ]:
#flatten : 1 row multiple column
a=a.flatten()
print(a)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
a=a.ravel()
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


ARRAY SLICING

In [ ]:
a=np.arange(1,51)
a=a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
a[0]

array([1, 2, 3, 4, 5])

In [ ]:
a[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
a[0,0]

np.int64(1)

In [ ]:
a[3,4]

np.int64(20)

In [ ]:
a[2:5] #rows 2nd index to 5-1 index

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])